name: library_controller
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  json_annotation: ^4.7.0
  provider: ^4.3.3

dev_dependencies:
  build_runner: ^1.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^3.5.1
  http_interceptor:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
